### ISSUE TITLE
Use `*.puml` as default extension for generated PlantUML files

### ISSUE THREAD

**Issue by poulhenriksen** [spring-projects-experimental/spring-modulith#120]
Currently, when generating the PlantUML diagrams with:

```Java
        new Documenter(modules)
                .writeModulesAsPlantUml()
                .writeIndividualModulesAsPlantUml()
        ;
```

It generates PlantUML files with `uml` as extension. According to https://plantuml.com/sources PlantUML files should use `pu` or `puml` as extension.

Using `uml` does, for example, not allow the IntelliJ PlantUML plugin to view the files, but renaming them to `puml` does.

Modulith can be configured to use `puml` like this:

```Java
        new Documenter(modules)
                .writeModulesAsPlantUml(Documenter.DiagramOptions.defaults().withTargetFileName("components.puml"))
                .writeIndividualModulesAsPlantUml(Documenter.DiagramOptions.defaults().withTargetFileName("module-%s.puml"))
        ;
```

But I think this should be the default.

**Comment by dusanradojcic00** [comment]
I could take this issue if that's okay.

**Comment by dusanradojcic00** [comment]
You can take it then, I don't have enough time today :)

**Comment by odrotbohm** [comment]
That's in place now.

**Comment by poulhenriksen** [comment]
That was fast. Thanks!
