### ISSUE TITLE
Oldest, uncompleted event publications should be returned first

### ISSUE THREAD

**Issue by ogawa-takeshi** [spring-projects-experimental/spring-modulith#133]
Migrated from https://github.com/moduliths/moduliths/issues/247.

Moduliths Events rerun incomplete domain events on reboot, but I think it's better to handle them starting with the oldest domain event on the publication date.

**Comment by odrotbohm** [comment]
Thanks, I took the chance to combine your production code changes with the tests inspired by your contribution to the legacy Moduliths projects.
