### ISSUE TITLE
How to use `ApplicationModuleDetectionStrategy.EXPLICITLY_ANNOTATED`?

### ISSUE THREAD

**Issue by marcantoine-bibeau** [spring-projects-experimental/spring-modulith#135]
I would like to use the ApplicationModuleDetectionStrategy.EXPLICITLY_ANNOTATED but it is package protected. 

Any workaround? 

Thanks in advance!

**Comment by odrotbohm** [comment]
The constants are exposed via `ApplicationModuleDetectionStrategy.explicitlyAnnotated()`/`….directSubPackage()`. Does that work for you?

**Comment by marcantoine-bibeau** [comment]
Ha! Totally, my bad did not realized! 

Thanks for your answer and continue to good work on this project :)
