### ISSUE TITLE
Using `spring-modulith-runtime` causes web application hangs on shutdown

### ISSUE THREAD

**Issue by razubuddy** [spring-projects-experimental/spring-modulith#145]
Use case:
Spring Boot Web application generated by Spring initializr https://start.spring.io/

Spring boot version `3.0.3`
Build tool: `gradle`
Dependencies: `Spring Web`, `Spring Data JPA`, `H2 Database`

Additional dependencies in build.gradle:
- `spring-modulith-starter-jpa` or `spring-modulith-starter-jdbc`
- `jmolecules-events`

Spring modulith modlues code from `spring-modulith-example` subproject

Changed `Application.java`:
```
@EnableAsync
@SpringBootApplication
@ConfigurationPropertiesScan
public class Application {

	public static void main(String[] args) {
		var app = SpringApplication.run(Application.class, args);
		if (args.length > 0 && "exit".equals(args[0])) {
			app.close();
		}
	}

}
```
`application.properties`:
```
spring.datasource.url=jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=FALSE
```

Running application: `./gradlew bootRun --args=exit`

With spring-modulith version `<= 0.3.0` application exits succesfully
With spring-modulith version `0.4.0` it hangs

**Comment by odrotbohm** [comment]
I've packaged up a release and it's on its way to Maven Central. Should be available within the next hour.
