### ISSUE TITLE
Support for JUnit 5 `@Nested` classes

### ISSUE THREAD

**Issue by midovlvn** [spring-projects-experimental/spring-modulith#173]
Hi, 

Nested classes does not works with Modulith 0.5

```
//@SpringBootTest - it works both nested and not-nested
@ApplicationModuleTest class MyBeanTest {

    @Test void test() {} // it pass

    @Nested class MyNested {

        @Test void nestedTest() {} // it fails
    }
}
```
> A component required a bean of type 'org.springframework.modulith.test.ModuleTestExecution' that could not be found.

**Comment by odrotbohm** [comment]
Thanks for bringing this up. That's in place in 0.6 snapshots if you want to give them a try.
