### ISSUE TITLE
Custom ApplicationModuleDetectionStrategy breaks cycle detection

### ISSUE THREAD

**Issue by mkonrad-dev** [spring-projects-experimental/spring-modulith#182]
Hello,

I've been experimenting with Spring Modulith in an existing Spring Boot project, and I have a need to override the standard module detection strategy as described in the [reference documentation](https://docs.spring.io/spring-modulith/docs/current-SNAPSHOT/reference/html/#fundamentals.customizing-modules).

After doing so, the modules seem to be correctly identified: 
- The generated `components.puml` diagram shows the desired modules
- Visibility constraints (no access to subpackages by default) are checked and violations are reported

_However, the cycle detection seems to be broken._

I created two Spring beans, one in each application module. I proceeded to inject them into each other, and calling each others methods. The Spring Boot application won't start and correctly report the cycle, but Spring Modulith won't, even tho the cycle is visible in the generated `components.puml` diagram.

When working with the default module detection strategy, this works correct and Spring Modulith will report an error.

At first glance, it seems that the module detection strategy plays no role in the cycle detection, instead it seems that an ArchUnit rule is being executed, that always only considers direct children of the root package (and optionally additional packages provided through the `Modulithic` annotation).

This leads to quite confusing behaviour in my project, which I tried to replicate in the following examples:
- When not using the `Modulithic` annotation to provide additional packages, the verification in [this example](https://github.com/mkonrad-dev/spring-modulith-demo/tree/904c938d4c730994a3eee1794cbea4f387efb994) does not report a cycle, when it should
- When using the `Modulithic` annotation to specify the parent package of `one` and `two` as an additional package, the Arch Unit rule will detect the cycle, but will also consider the package `three`, which was never detected as a module by the custom `ApplicationModuleDetectionStrategy` (see [example](https://github.com/mkonrad-dev/spring-modulith-demo/tree/b4b90140362497408347e64efd8acd81b25bf2d9))
- When components with cycles are defined at various package depths, the cycle detection will (sometimes) report a cycle between "slices", that are not themselves modules (see [example](https://github.com/mkonrad-dev/spring-modulith-demo/tree/3e274f762577fb80ddf8c6a4cd7dced2385e4523))

I believe that all of this would be addressed, if cycle detection would solely check cycles between modules detected by the (custom) `ApplicationModuleDetectionStrategy`, instead of relying on a completely separate mechanism, that only works for the default `ApplicationModuleDetectionStrategy`.

**Comment by odrotbohm** [comment]
Good catch! Would you mind trying the latest snapshots? I've applied a fix and your sample project now shows the expected behavior (all examples properly reporting the "one <-> two" cycle).

**Comment by mkonrad-dev** [comment]
Thanks for the quick fix!

Can confirm that all examples work as expected with the 0.6.0-SNAPSHOT
