### ISSUE TITLE
Event Publication Registry stores mapping events from Spring Data Relational

### ISSUE THREAD

**Issue by xjianyu** [spring-projects-experimental/spring-modulith#186]
When using spring data jdbc to save entities, the EVENT_PUBLICATION table will save springframework events. Is this normal?
<img width="428" alt="image" src="https://user-images.githubusercontent.com/19404942/234794204-b983f8c6-20ff-42ed-905e-95ff66f647ce.png">

**Comment by odrotbohm** [comment]
This seems to be caused by spring-projects/spring-framework#30399. I have a fix local to our event multicasting infrastructure available that we can use until the upstream ticket is fixed.

**Comment by odrotbohm** [comment]
This should work better now. Please give the latest snapshots a try.
