### ISSUE TITLE
`EvenPublication` lookup might fail if domain events are not entirely unique

### ISSUE THREAD

**Issue by dmbelyaev** [spring-projects-experimental/spring-modulith#25]
Currently, we do not imply any constraints on the domain events to get publications registered for. This results in the potential case of an event published twice and us creating publications for the same event representation and publication target identifier (PTI). The lookup of an event publication to mark it completed currently assumes to find a unique entry per event and PTI, which we cannot actually rely on.

As a mitigating measure, it makes sense to at least let the lookup filter for uncompleted events so that we would at least select an uncompleted publication to eventually be marked as completed. As there's still a chance that even in the case of multiple publications for the same logical event, concurrent readers might lookup the same database row and leave one publication incomplete, we need to highly recommend to use unique event instances.

**Comment by odrotbohm** [comment]
That's polished and merged.
