### ISSUE TITLE
Modulith in multi-module projects

### ISSUE THREAD

**Issue by victorherraiz-santander** [spring-projects-experimental/spring-modulith#54]
What could be the relationship with a maven multi module project? 

I normally divide big projects in several modules (mainly by functional packages) and clearly describe the dependencies between them in the `pom.xml`, avoiding some strange dependency cycles and other problems in long run developments.

**Comment by odrotbohm** [comment]
Would you mind raising such questions on stackoverflow.com instead? We would like to keep the issue tracker focussed on actionable tickets, capture ideas, report bugs etc.

**Comment by yossisp** [comment]
@odrotbohm Can you please create `spring-modulith` tag in SO? I don't have enough reputation to do that.
