### ISSUE TITLE
Page at https://spring.io/projects/spring-modulith#learn does not show 0.1 release

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-projects-experimental/spring-modulith#83]
Currently only the SNAPSHOT version and the RC version are shown [there](https://spring.io/projects/spring-modulith#learn):

<img width="892" alt="image" src="https://user-images.githubusercontent.com/1115823/204531708-b54d0d0f-19ef-47bc-a192-f9771560897f.png">

**Comment by odrotbohm** [comment]
That's fixed. Thanks for the heads up!
